version: '3'
services:
  redis:
    image: redis:7.4.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql

networks:
  default:
    driver: bridge